# Generated by KROKI
# http://www.kroki-mde.net/

#default imports
from django import forms
from django.forms.widgets import TextInput, Textarea, Select, DateInput, NumberInput, CheckboxInput
from django.utils import timezone


#generated imports
from ${modulename}.models import Login<#list models as model>, ${model.name}</#list>

# Default Login form
class LoginForm(forms.ModelForm):
	class Meta:
		model = Login
		fields = ['username', 'password']
    
	def clean_password(self):
		password = self.cleaned_data.get('password')
    
	def clean_username(self):
		username = self.cleaned_data.get('username')

<#list models as model>
class ${model.name}Form(forms.ModelForm):
	class Meta:
		model = ${model.name}
		fields =[
			<#list model.fieldsList as field>
			'${field.fieldName}'<#if field_has_next == true>,</#if>
			</#list>
		]
		
		widgets = {
		<#list model.fieldsList as field>
		<#if field.entryTypesEnum == 'CharField'>
			'${field.fieldName}' : TextInput(attrs={'class':'form-control'}),
		<#elseif field.entryTypesEnum == 'IntegerField'>
			'${field.fieldName}' : NumberInput(attrs={'class':'form-control'}),
		<#elseif field.entryTypesEnum == 'DateField'>
		<#elseif field.entryTypesEnum == 'FloatField'>
		<#elseif field.entryTypesEnum == 'BooleanField'>
			'${field.fieldName}' : CheckboxInput(attrs={'class':'form-control'}),
		<#elseif field.entryTypesEnum == 'ForeignKey'>
		</#if>
		</#list>
		}

</#list>
    