from django.db import models

# Generated by KROKI
# http://www.kroki-mde.net/

from django.contrib.auth.models import User
    
class Login(models.Model):
	username = models.CharField(max_length = 60, blank=True, null=False)
	password = models.CharField(max_length = 60, blank=True, null=False)
	
	def __str__(self):
		return self.username

class Article(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateField()

    def get_absolute_url(self):
        return reverse('article-detail', kwargs={'pk': self.pk})
        		
<#list models as model>
class ${model.name}(models.Model):
<#list model.fieldsList as field>
<#if field.entryTypesEnum == 'CharField'>
	${field.fieldName} = models.${field.entryTypesEnum}(max_length = <#if field.length == 0>255<#else>${field.length}</#if><#if field.key == true>, primary_key = True</#if>)
<#elseif field.entryTypesEnum == 'IntegerField'>
<#elseif field.entryTypesEnum == 'DateField'>
<#elseif field.entryTypesEnum == 'FloatField'>
<#elseif field.entryTypesEnum == 'BooleanField'>
<#elseif field.entryTypesEnum == 'ForeignKey'>
</#if>	
</#list>	

	def __str__(self):
		return '${model.name}:'<#list model.fieldsList as field> + '${field.fieldName}' = self.${field.fieldName}.__str__()</#list>
		
</#list>
