
# Generated by KROKI
# http://www.kroki-mde.net/

from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, render
from django.contrib.auth import authenticate, login, logout
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from .forms import LoginForm 

# homepage view
@login_required(login_url='/login/')
def index(request):
	context = {
		"projectname": "${projectname}",
	}
	return render(request,'home.html', context)

# logout function	
def logout_user(request):
	form = LoginForm()
	context = {
		"projectname": "${projectname}",
		"description": "${description}", 	
		"title": 'Login',
		"form" : form
    }
    
	logout(request)
	return render(request,'login.html', context)     
 
# test link for sanity checks            
def testdefault(request):
	return HttpResponse("Hello, world. You're at the test view.")
	
# login function
def login_user(request):   
	form = LoginForm()
	context = {
		"projectname": "${projectname}",
		"description": "${description}",  	
		"title": 'Login',
		"form" : form
    }
	username = password = ''
	if request.POST:
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('index'))
	return render(request,'login.html', context)

<#list urls as url>	
def ${url.view}_list(request):
    context = RequestContext(request)
    citys = City.objects.all()    
    return render_to_response('${modulename}/cityList.html',{'deletable' : "true", "citys" : citys},context)
</#list>



<#list urls as url>	
# Display ${url.view} list form
@login_required(login_url='/login/')
def ${url.view}(request):
	model = ${url.view}
        
	context = {
		"projectname": "${projectname}",
		"title": 'Login',
	#	"form" : form
    }
	return render(request,'form.html', context)

# Display ${url.view} add form
@login_required(login_url='/login/')	
def ${url.view}_new(request): 
	form = ${url.view}Form()
	context = {
		"projectname": "${projectname}",
		"title": 'Login',
	#	"form" : form
    }
	return render(request,'form.html', context)
	
# Display ${url.view} edit form
@login_required(login_url='/login/')	
def ${url.view}_edit(request):
	form = ${url.view}Form()
	context = {
		"projectname": "${projectname}",
		"title": 'Login',
	#	"form" : form
    } 
	return render(request,'form.html', context)

</#list>

   

	