# Generated by KROKI
# http://www.kroki-mde.net/

from django import forms
from .models import Login

# Login form
class LoginForm(forms.ModelForm):
	class Meta:
		model = Login
		fields = ['username', 'password']
    
	def clean_password(self):
		password = self.cleaned_data.get('password')
    
	def clean_username(self):
		username = self.cleaned_data.get('username')
    
