# Generated by KROKI
# http://www.kroki-mde.net/

from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, render
from django.contrib.auth import authenticate, login, logout
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from .forms import LoginForm 

# homepage view
@login_required
def index(request):
	projectname = "${projectname}"
	context = {
		"projectname": projectname 
	}
	return render(request,'home.html', context)

# login view
def login(request):

	form = LoginForm()
	
	context = {
		"title": title,
		"form": form
	}
	return render(request, 'login.html', context)
	
# logout function	
def logout_user(request):
    logout(request)    

def auth_view(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username = username, password = password)      

    if user is not None:
        auth.login(request, user)
        return HttpResponseRedirect(reverse('home'))
    else:
        return HttpResponseRedirect('/accounts/invalid')
            
def testdefault(request):
	return HttpResponse("Hello, world. You're at the test view.")

def login_user(request):
	title = 'Login'
   
	form = LoginForm()
	context = {
		"title": title,
		"form" : form
    }
	username = password = ''
	if request.POST:
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect('/index')
	return render(request,'login.html', context)
	
