# Generated by KROKI
# http://www.kroki-mde.net/

from django import forms
from .models import Login
from .models import Author
from django.views.generic.edit import CreateView

# Login form
class LoginForm(forms.ModelForm):
	class Meta:
		model = Login
		fields = ['username', 'password']
    
	def clean_password(self):
		password = self.cleaned_data.get('password')
    
	def clean_username(self):
		username = self.cleaned_data.get('username')
    
class AuthorCreate(CreateView):
    model = Author
    fields = ['name']