# Generated by KROKI
# http://www.kroki-mde.net/

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from testProject007 import views

from django.contrib import admin
admin.autodiscover()

from .views import ArticleListView,AuthorCreate

urlpatterns = patterns('',
    # login / logout
    
    #Links for filename007_st
    url(r'^filename007_st', 'testProject007.views.filename007_st', name='filename007_st'),   
    url(r'^filename007_st_new', 'testProject007.views.filename007_st_new', name='filename007_st_new'),   
    url(r'^filename007_st_edit', 'testProject007.views.filename007_st_edit', name='filename007_st_edit'),     
   
   	# home page
    url(r'^$', 'testProject007.views.index', name='index'),
    
   	# test url
 	url(r'^test', views.testdefault),
 	
 	# Set Django login and logout links
    url(r'^logout/$', 'testProject007.views.logout_user', name='logout'),
    url(r'^login/$', 'testProject007.views.login_user', name='login'),
    
	url(r'^admin/', include(admin.site.urls)),
  
  	url(r'^articles', ArticleListView.as_view(), name='article-list'),
  	url(r'^authorCreate', AuthorCreate.as_view(), name='author-create'),
) 
